# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea6614ee316391789d773da7ba6e1c17440512dc82ef00af424ebc36c3f141db12a7e791cccb8d98e17e071a4a07df9b45fa467179fe445a7ec8affd434033fe

test:
  secret_key_base: 6451658dd238327008ac342809cb6913a26596798adb35ddc99a436f720818e8971169e541a46e6fcb9b66945440cbfd46323d11a12ffb3d4c353b4ac7d3b9c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
